export default {
  Code: '',
  Name: '',
  Photo: '',
  Birthday: '',
  MaritalStatus: '',
  PersonalityType: '',
  BloodGroup: '',
  CitizenshipNo: '',
  EmailId: '',
  LocalAddress: '',
  LocalAddressContactNo: '',
  LocalAddressMobileNo: '',
  PermanentAddress: '',
  PermanentAddressContactNo: '',
  PermanentAddressMobileNo: '',
  EmergencyAddress: '',
  EmergencyAddressContactNo: '',
  EmergencyAddressMobileNo: '',
  GooglePlusLink: '',
  FacebookLink: '',
  TwitterLink: '',
  LinkedInLink: ''
}
